### ISSUE TITLE
Whoops - 404s

### ISSUE THREAD

**Issue by markoprodanovic** [saud-learning-services/saud-learning-services.github.io#8]
Whoops something in the last merge messed with our links. Likely a small naming thing or files in the wrong location.

@markoprodanovic to investigate 

<img width="977" alt="Screen Shot 2021-01-13 at 1 12 45 PM" src="https://user-images.githubusercontent.com/22332030/104511066-08c29e80-55a1-11eb-899d-e51535302689.png">

**Comment by markoprodanovic** [comment]
It is possible that removing the dates from the start of the .md files caused the issue. I'll follow up once I know more.

Jekyll is very opinionated in how things are named and projects are structured

<img width="463" alt="Screen Shot 2021-01-13 at 1 14 42 PM" src="https://user-images.githubusercontent.com/22332030/104511324-62c36400-55a1-11eb-8217-c18ae9d029e9.png">

I will follow up

**Comment by alisonmyers** [comment]
I think it is the date thing - Change the file name to include today’s date and the title of your post. Jekyll requires posts to be named year-month-day-title.md.
1:59
https://www.smashingmagazine.com/2014/08/build-blog-jekyll-github-pages/
